/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteImport } from "./routes/_dashboard";
import { Route as DashboardDashboardAnalyticsRouteImport } from "./routes/_dashboard.dashboard.analytics";
import { Route as DashboardDashboardIndexRouteImport } from "./routes/_dashboard.dashboard.index";
import { Route as DashboardDashboardProfileRouteImport } from "./routes/_dashboard.dashboard.profile";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as SetupRouteImport } from "./routes/setup";

const SetupRoute = SetupRouteImport.update({
	id: "/setup",
	path: "/setup",
	getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
	id: "/login",
	path: "/login",
	getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
	id: "/_dashboard",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
	id: "/dashboard/",
	path: "/dashboard/",
	getParentRoute: () => DashboardRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
	id: "/api/auth/$",
	path: "/api/auth/$",
	getParentRoute: () => rootRouteImport,
} as any);
const DashboardDashboardProfileRoute =
	DashboardDashboardProfileRouteImport.update({
		id: "/dashboard/profile",
		path: "/dashboard/profile",
		getParentRoute: () => DashboardRoute,
	} as any);
const DashboardDashboardAnalyticsRoute =
	DashboardDashboardAnalyticsRouteImport.update({
		id: "/dashboard/analytics",
		path: "/dashboard/analytics",
		getParentRoute: () => DashboardRoute,
	} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/setup": typeof SetupRoute;
	"/dashboard/analytics": typeof DashboardDashboardAnalyticsRoute;
	"/dashboard/profile": typeof DashboardDashboardProfileRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
	"/dashboard": typeof DashboardDashboardIndexRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/login": typeof LoginRoute;
	"/setup": typeof SetupRoute;
	"/dashboard/analytics": typeof DashboardDashboardAnalyticsRoute;
	"/dashboard/profile": typeof DashboardDashboardProfileRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
	"/dashboard": typeof DashboardDashboardIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/_dashboard": typeof DashboardRouteWithChildren;
	"/login": typeof LoginRoute;
	"/setup": typeof SetupRoute;
	"/_dashboard/dashboard/analytics": typeof DashboardDashboardAnalyticsRoute;
	"/_dashboard/dashboard/profile": typeof DashboardDashboardProfileRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
	"/_dashboard/dashboard/": typeof DashboardDashboardIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/login"
		| "/setup"
		| "/dashboard/analytics"
		| "/dashboard/profile"
		| "/api/auth/$"
		| "/dashboard";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/login"
		| "/setup"
		| "/dashboard/analytics"
		| "/dashboard/profile"
		| "/api/auth/$"
		| "/dashboard";
	id:
		| "__root__"
		| "/"
		| "/_dashboard"
		| "/login"
		| "/setup"
		| "/_dashboard/dashboard/analytics"
		| "/_dashboard/dashboard/profile"
		| "/api/auth/$"
		| "/_dashboard/dashboard/";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	DashboardRoute: typeof DashboardRouteWithChildren;
	LoginRoute: typeof LoginRoute;
	SetupRoute: typeof SetupRoute;
	ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/setup": {
			id: "/setup";
			path: "/setup";
			fullPath: "/setup";
			preLoaderRoute: typeof SetupRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_dashboard": {
			id: "/_dashboard";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof DashboardRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_dashboard/dashboard/": {
			id: "/_dashboard/dashboard/";
			path: "/dashboard";
			fullPath: "/dashboard";
			preLoaderRoute: typeof DashboardDashboardIndexRouteImport;
			parentRoute: typeof DashboardRoute;
		};
		"/api/auth/$": {
			id: "/api/auth/$";
			path: "/api/auth/$";
			fullPath: "/api/auth/$";
			preLoaderRoute: typeof ApiAuthSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_dashboard/dashboard/profile": {
			id: "/_dashboard/dashboard/profile";
			path: "/dashboard/profile";
			fullPath: "/dashboard/profile";
			preLoaderRoute: typeof DashboardDashboardProfileRouteImport;
			parentRoute: typeof DashboardRoute;
		};
		"/_dashboard/dashboard/analytics": {
			id: "/_dashboard/dashboard/analytics";
			path: "/dashboard/analytics";
			fullPath: "/dashboard/analytics";
			preLoaderRoute: typeof DashboardDashboardAnalyticsRouteImport;
			parentRoute: typeof DashboardRoute;
		};
	}
}

interface DashboardRouteChildren {
	DashboardDashboardAnalyticsRoute: typeof DashboardDashboardAnalyticsRoute;
	DashboardDashboardProfileRoute: typeof DashboardDashboardProfileRoute;
	DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
	DashboardDashboardAnalyticsRoute: DashboardDashboardAnalyticsRoute,
	DashboardDashboardProfileRoute: DashboardDashboardProfileRoute,
	DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
	DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	DashboardRoute: DashboardRouteWithChildren,
	LoginRoute: LoginRoute,
	SetupRoute: SetupRoute,
	ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
